Added prototype comparison page
goodmeh/goodmeh-frontend pull request #23
Opened 2024-09-17 15:40 UTC by SethCKL

Abstracted existing search location functionality into a PlaceSearch component for repeated use

Implemented a MantineTable component using Mantine React Table also for repeated use

2024-09-17 15:49 UTC, zhekaiii requested changes
Hi, I know this is just an early prototype but here are my comments :)

2024-09-17 15:49 UTC, zhekaiii commented on src/components/ui/MantineTable.tsx
Do you think we can name this a little bit more specific? Like `PlaceComparisonTable`?

2024-09-17 15:49 UTC, zhekaiii commented on src/components/ui/MantineTable.tsx
> +export default function App() {
Let's stick to our usual convention of declaring Functional Components, and also please name the component properly :)
```suggestion
export const PlaceComparisonTable: React.FC = () => {
```

2024-09-17 15:49 UTC, zhekaiii commented on src/components/ui/MantineTable.tsx
> +interface Compare {
Compare is a verb, not the most suitable for naming after types. Also, sorry for another unspoken rule/convention but let's use typescript `types` over `interfaces`

2024-09-18 15:31 UTC, zhekaiii commented
![image](https://github.com/user-attachments/assets/b7151024-211b-47e9-bc06-c8383d115a79)
Can you also find some way to hide this? Or we do in a future PR when we put actual data in?

2024-09-18 20:26 UTC, SethCKL commented
Yes actually! but i couldn't figure out how to only make it display only when two places have been selected

2024-09-23 07:04 UTC, zhekaiii approved these changes
LGTM, thanks!

2024-09-23 07:05 UTC, merged