Dashboard version 1
goodmeh/goodmeh-frontend pull request #37
Opened 2024-09-26 10:37 UTC by SethCKL

add for new components to display data

- CountBasedChart
- CriteriaBasedChart
-PercentageBasedChart
-TimeBasedChart

these components are used for the Dashboard page and a initial version can be found at /dashboard

2024-10-03 07:36 UTC, zhekaiii requested changes
Just some minor nitpick on UI. Also, can you experiment with larger gaps? Looks quite claustrophobic here. Thanks!
![image](https://github.com/user-attachments/assets/6e04e8d9-d5a6-4d28-8a1c-7a99e3e0af1b)

2024-10-03 07:36 UTC, zhekaiii commented on src/components/data/PercentageBasedChart.tsx
> +        h={400}
I think this is not needed, the height comes from the `size` prop already. That's why there was a lot of space between the title and the chart
![image](https://github.com/user-attachments/assets/c2ecadfb-bb3f-4879-bcfe-ad57ea25d40b)

2024-10-03 07:36 UTC, zhekaiii commented on src/index.scss
> +  font-size: 1.25rem;
I think 1rem looks better here

2024-10-07 05:22 UTC, SethCKL commented on src/components/data/PercentageBasedChart.tsx
> +        h={400}
good catch! height indeed was redundant

2024-10-07 05:26 UTC, SethCKL commented on src/index.scss
> +  font-size: 1.25rem;
agreed!

2024-10-07 10:32 UTC, zhekaiii requested changes
Minor nits

2024-10-07 10:32 UTC, zhekaiii commented on src/app/pages/Dashboard.page.tsx
> +          data={[
Do you think it would be better to shift this hardcoded data out of the component?

2024-10-07 11:13 UTC, SethCKL commented on src/app/pages/Dashboard.page.tsx
> +          data={[
yes i do think so, great catch

2024-10-07 11:16 UTC, SethCKL commented
let's not merge this until we plug in real data

2024-10-25 13:39 UTC, SethCKL commented
This is no longer a dashboard page, but rather due to UI and UX changes has become a component and is rendered on the search screen

2024-10-26 03:23 UTC, zhekaiii requested changes
Thanks for the hard work, here are some comments from me

2024-10-26 03:23 UTC, zhekaiii commented on src/features/Dashboard/api/getReviewAge.ts
> +    `/v1/dashboard/review-age/${placeId}`,
This url is wrong btw it's supposed to be `yearly-reviews` and the data shape is wrong also, it's supposed to be `Record<string, number>` where the key is the year in string and the value is the count. But since this is not in use I guess we can delete this file?

2024-10-26 03:23 UTC, zhekaiii commented on src/features/Dashboard/components/StatSection.tsx
> +  const placeId = place?.id;
Minor nitpick but unnecessary optional chaining (`?.`) because place can't be null.

2024-10-26 03:23 UTC, zhekaiii commented on src/features/Dashboard/api/getRatingTrend.ts
> +  name: string;
This shape looks wrong also

2024-10-26 13:43 UTC, SethCKL commented on src/features/Dashboard/api/getReviewAge.ts
> +    `/v1/dashboard/review-age/${placeId}`,
oh yes, lets remove this!

2024-10-26 13:44 UTC, SethCKL commented on src/features/Dashboard/components/StatSection.tsx
> +  const placeId = place?.id;
gotcha! removed the optional chaining 👍

2024-10-26 14:19 UTC, SethCKL commented on src/features/Dashboard/api/getRatingTrend.ts
> +  name: string;
not sure if the endpoint format changed a little, but all good i have updated~

2024-10-26 14:31 UTC, zhekaiii approved these changes
LGTM, I think I will merge this after https://github.com/goodmeh/goodmeh-backend/pull/176#event-14879192935 gets merged

2024-10-26 18:49 UTC, SethCKL commented
https://github.com/goodmeh/goodmeh-backend/pull/176 has been merged, so i shall do the same for this!

2024-10-26 18:49 UTC, merged